# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasosDeUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosDgsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cumplido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosParque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cumplido', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='requisitosdgsm',
            name='requisitos_dgsm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.RequisitosParque'),
        ),
        migrations.AddField(
            model_name='casosdeuso',
            name='requisitos_parque',
            field=models.ManyToManyField(to='actividades.RequisitosDgsm'),
        ),
    ]
