# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequisitosDgsm',
            new_name='ReqDgsm',
        ),
        migrations.RenameModel(
            old_name='RequisitosParque',
            new_name='ReqParque',
        ),
        migrations.RenameField(
            model_name='casosdeuso',
            old_name='requisitos_parque',
            new_name='req_parque',
        ),
        migrations.RenameField(
            model_name='reqdgsm',
            old_name='requisitos_dgsm',
            new_name='req_dgsm',
        ),
    ]
