# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20161005_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casosdeuso',
            old_name='req_parque',
            new_name='req_dgsm',
        ),
        migrations.RenameField(
            model_name='reqdgsm',
            old_name='req_dgsm',
            new_name='req_parque',
        ),
    ]
