# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqdgsm',
            name='req_parque',
        ),
        migrations.AddField(
            model_name='reqparque',
            name='req_dgsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.ReqDgsm'),
        ),
    ]
