# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_auto_20161006_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='casosdeuso',
            options={'verbose_name_plural': 'Casos de Uso'},
        ),
        migrations.AlterModelOptions(
            name='reqdgsm',
            options={'verbose_name_plural': 'Requisitos DGSM'},
        ),
        migrations.AlterModelOptions(
            name='reqparque',
            options={'verbose_name_plural': 'Requisitos ParqueSoft'},
        ),
    ]
